[Spinner] add logic first visit, refactoring
kapitoshka24/event-booster pull request #27
Opened 2021-05-13 16:27 UTC by IvanVA13

2021-05-14 22:31 UTC, kapitoshka24 requested changes

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/eventRender.js
> +  showHideSpinner("remove")
может лучше назвать `toggleSpinner()`? 
немного сбивает с толку show и hide одновременно, лучше чтоб это было одним словом

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/eventRender.js
> +    showHideSpinner("add")
аналогично выше

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/spinner.js
> +const addClassSpinner = (search, type, clas) => {
`class` с двумя s)

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/spinner.js
> +    document.querySelector(search).classList[type](clas)
Лучше убрать параметр type, ты ведь используешь функцию только для добавления класса) 
`document.querySelector(search).classList.add(class)`

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/spinner.js
> +    document.querySelector(search).classList[type](clas)
Также как class можно просто сразу передать `first-visit`, и функцию переназвать соответсвенно, так как ты используешь ее только для этого) Но идея крутая, можешь оставить, если хочешь)

2021-05-14 22:31 UTC, kapitoshka24 commented on src/js/storage.js
> +            return undefined
Лучше не возвращать undefined, а делать console.log ошибки

2021-05-15 06:07 UTC, IvanVA13 commented on src/js/eventRender.js
> +  showHideSpinner("remove")
toggleSpinner -- лучше) исправил

2021-05-15 06:08 UTC, IvanVA13 commented on src/js/spinner.js
> +const addClassSpinner = (search, type, clas) => {
class -- зарезирвированный параметр)

2021-05-15 06:09 UTC, IvanVA13 commented on src/js/spinner.js
> +    document.querySelector(search).classList[type](clas)
сама ф-я -- задел на рефакторинг. Но в контексте спиннера конечно type лишний, убрал.
по 2му замечанию тоже подправил

2021-05-15 09:00 UTC, IvanVA13 commented on src/js/storage.js
> +            return undefined
для setItem исправил, а для getItem там нужно чтобы возвращал undefined. Брал у Веника

2021-05-15 10:57 UTC, closed without merging